<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DvmConsole.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../native/dvmaudio-pipewire/managed-exports.txt"
                      Link="Native/managed-exports.txt"
                      LogicalName="DvmConsole.Audio.Linux.ManagedExports.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio.Abstractions/DvmConsole.Audio.Abstractions.csproj" />
    <ProjectReference Include="../DvmConsole.Audio.Core/DvmConsole.Audio.Core.csproj" />
  </ItemGroup>
</Project>
