<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RuntimeIdentifiers>osx-arm64;osx-x64</RuntimeIdentifiers>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Copyright>Copyright (c) 2025 Caleb, K4PHP and DVMProject (https://github.com/dvmproject) Authors.</Copyright>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <Title>Digital Voice Modem - Desktop Dispatch Console (Avalonia Shell)</Title>
    <Authors>Caleb, K4PHP and DVMProject (https://github.com/dvmproject) Authors</Authors>
    <Company>DVMProject</Company>
    <Product>Digital Voice Modem - Desktop Dispatch Console (Avalonia Shell)</Product>
    <RepositoryUrl>https://github.com/DVMProject/dvmconsole</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.18" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DvmConsole.Core\DvmConsole.Core.csproj" />
    <ProjectReference Include="..\DvmConsole.Platform\DvmConsole.Platform.csproj" />
  </ItemGroup>

</Project>
