<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DvmConsole.FneClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.Fne/DvmConsole.Fne.csproj" />
  </ItemGroup>
</Project>
