<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>DvmConsole.FneClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.Fne/DvmConsole.Fne.csproj" />
  </ItemGroup>
</Project>
