<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DvmConsole.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio.Abstractions/DvmConsole.Audio.Abstractions.csproj" />
  </ItemGroup>
</Project>
