<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>DvmConsole.AudioProbe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio/DvmConsole.Audio.csproj" />
  </ItemGroup>
</Project>
