<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DvmConsole.Operations</RootNamespace>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
  </ItemGroup>
</Project>
