<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DvmConsole.Ptt</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Ptt.Abstractions/DvmConsole.Ptt.Abstractions.csproj" />
  </ItemGroup>
</Project>
