<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DvmConsole.FneProbe</RootNamespace>
    <AnalysisMode>None</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.FneClient/DvmConsole.FneClient.csproj" />
  </ItemGroup>
</Project>
