<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Copyright>Copyright (c) 2025 Caleb, K4PHP and DVMProject (https://github.com/dvmproject) Authors.</Copyright>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <Title>Digital Voice Modem - Desktop Dispatch Console Core</Title>
    <Authors>Caleb, K4PHP and DVMProject (https://github.com/dvmproject) Authors</Authors>
    <Company>DVMProject</Company>
    <Product>Digital Voice Modem - Desktop Dispatch Console Core</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.2.0" />
  </ItemGroup>

</Project>
