<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>DvmConsole.Desktop</RootNamespace>
    <AssemblyName>DvmConsole</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets/DVMConsole.ico</ApplicationIcon>
    <Authors>RdWing</Authors>
    <Company>DVMProject</Company>
    <Product>Digital Voice Modem - Desktop Dispatch Console</Product>
    <AssemblyTitle>DVM Console</AssemblyTitle>
    <Copyright>Copyright © 2025-2026 RdWing</Copyright>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/RdWing/dvmconsole</RepositoryUrl>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Markdown.Avalonia" Version="11.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio/DvmConsole.Audio.csproj" />
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.FneClient/DvmConsole.FneClient.csproj" />
    <ProjectReference Include="../DvmConsole.Media/DvmConsole.Media.csproj" />
    <ProjectReference Include="../DvmConsole.Vocoder/DvmConsole.Vocoder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/DVMConsole.png" />
    <None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../NOTICES.md" Link="NOTICES.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
