<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DvmConsole.MediaProbe</RootNamespace>
    <AnalysisMode>None</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio/DvmConsole.Audio.csproj" />
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.FneClient/DvmConsole.FneClient.csproj" />
    <ProjectReference Include="../DvmConsole.Media/DvmConsole.Media.csproj" />
    <ProjectReference Include="../DvmConsole.Vocoder/DvmConsole.Vocoder.csproj" />
  </ItemGroup>
</Project>
