<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DvmConsole.MediaProbe</RootNamespace>
    <AnalysisMode>None</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Audio.Abstractions/DvmConsole.Audio.Abstractions.csproj" />
    <ProjectReference Include="../DvmConsole.Audio.Core/DvmConsole.Audio.Core.csproj" />
    <ProjectReference Include="../DvmConsole.Audio.Desktop/DvmConsole.Audio.Desktop.csproj" />
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <ProjectReference Include="../DvmConsole.FneClient/DvmConsole.FneClient.csproj" />
    <ProjectReference Include="../DvmConsole.Media/DvmConsole.Media.csproj" />
    <ProjectReference Include="../DvmConsole.Vocoder.Abstractions/DvmConsole.Vocoder.Abstractions.csproj" />
    <ProjectReference Include="../DvmConsole.Vocoder.Native/DvmConsole.Vocoder.Native.csproj" />
  </ItemGroup>
</Project>
