<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DvmConsole.Core/DvmConsole.Core.csproj" />
    <None Include="../../configs/codeplug.example.yml" Link="TestData/codeplug.example.yml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../configs/keys.example.clear" Link="TestData/keys.example.clear" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../configs/alias.example.yml" Link="TestData/alias.example.yml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="TestData/Compatibility/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
